### ISSUE TITLE
"Fog_Settings.xml" not found

### ISSUE THREAD

**Issue by edap** [roymacdonald/ofxGLFog#1]
Hi, I'm trying to use this addon with OF 0.9.8. I've ofxGui as dependency but I still have this error:

```
[ error ] ofXml: couldn't load, "Fog_Settings.xml" not found
[warning] ofXml: setTo(): empty document
```

Adding the missing file to the `bin/data` folder does not solve the problem

**Comment by roymacdonald** [comment]
Hi, it's because you haven't saved what's on the gui. press the save button on the gui and the next time you run the app you wont see this error.

**Comment by edap** [comment]
Yes, drawing the GUI and saving the parameters fix the error message. I can see the fog working in the example app. But I can not have this addon working in the programmable pipeline, is there any workaround?

**Comment by roymacdonald** [comment]
Hi, it is because this addon uses a deprecated fixed-pipeline function.
for programmable pipeline  you'll need to write a shader for it.
from a fast google search I found the following useful links. Hope this helps
http://stackoverflow.com/questions/21549456/how-to-implement-a-ground-fog-glsl-shader
http://www.iquilezles.org/www/articles/fog/fog.htm

best!

**Comment by edap** [comment]
Yes, i will go for this solution. Thanks ;)

**Comment by roymacdonald** [comment]
if get it to work it would be great if you want to add the programmable pipeline implementation to this addon.
best!
